services:
  - type: web
    name: gffh-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
